### ISSUE TITLE
unzip dataset

### ISSUE THREAD

**Issue by zxy110** [yipoh/AesBench#1]
Hi, 
Great work! Thanks for your contribution. But when I unzip the dataset, it needs a password, will u make it publicly?
thanks,
zxy

**Comment by dylanqyuan** [comment]
> Hi, Great work! Thanks for your contribution. But when I unzip the dataset, it needs a password, will u make it publicly? thanks, zxy

Hey zxy!
Thanks for you attention! 
please submit the request for access through https://github.com/yipoh/AesBench/blob/main/data_release/README.md.
We are looking forward to see your MLLM in the latest leaderboard! :laughing:
