### ISSUE TITLE
unzip password

### ISSUE THREAD

**Issue by QLYYLQ** [yipoh/AesBench#10]
您好，我这边想使用您的数据集作为我们的一个评判标准，请问可以给我解压密码吗 :-)

**Comment by dylanqyuan** [comment]
您好，感谢您对AesBench的关注！
请您根据[这个链接](https://github.com/yipoh/AesBench/tree/main/data_release)提供的方式提交相关信息，我们会尽快审核。
值得注意的是 任何包含非真实陈述的申请都将被视为无效申请。
