### ISSUE TITLE
unzip password

### ISSUE THREAD

**Issue by yangmmm** [yipoh/AesBench#3]
Hi,
Great work! Thanks for your contribution. I have sent a download application email to huangyipo@stu.xidian.edu.cn, but did not get a reply. can you provide the unzip password?
Thanks！

**Comment by yipoh** [comment]
Thanks for your attention! 😄

**Comment by yipoh** [comment]
> Hi, Great work! Thanks for your contribution. I have sent a download application email to [huangyipo@stu.xidian.edu.cn](mailto:huangyipo@stu.xidian.edu.cn), but did not get a reply. can you provide the unzip password? Thanks！

Thanks for your attention! 😄 The unzip password has been replied by email.

**Comment by yangmmm** [comment]
My problem has been solved.
